deploy: add job to deploy on cloud run

diff --git a/.github/workflows/multi_job_ci_cd.yaml b/.github/workflows/multi_job_ci_cd.yaml
--- a/.github/workflows/multi_job_ci_cd.yaml
+++ b/.github/workflows/multi_job_ci_cd.yaml
@@ -1,8 +1,19 @@
-name: CI MLOps
+name: CI/CD MLOps
 
 on:
+  pull_request:
+    branches:
+      - main
   push:
-    branches: dev
+    branches:
+      - dev
+    
+  workflow_dispatch:
+    inputs:
+      environment:
+        description: 'Environment to deploy to'
+        required: true
+        default: 'production'
 
 defaults:
   run:
@@ -37,8 +48,8 @@ jobs:
         uses: 'google-github-actions/auth@v2'
         with:
           project_id: ${{ secrets.GCP_PROJECT_ID }}
-          workload_identity_provider: 'projects/343693069423/locations/global/workloadIdentityPools/github/providers/mlops'
-          service_account: 'model-884@mlops-413215.iam.gserviceaccount.com'
+          workload_identity_provider: '${{ GCP_WORKLOAD_IDENTITY_PROVIDER }}'
+          service_account: '${{ GCP_SERVICE_ACCOUNT_EMAIL }}'
 
 
   code-quality:
@@ -48,10 +59,23 @@ jobs:
       - name: Checkout Repository
         uses: actions/checkout@v4
         
+      - name: Install dependencies
+        run: |
+          pip install pycodestyle isort
+        
       - name: Linting
         run: |
-            pip install pycodestyle==2.11.1 isort==5.13.2
-            pycodestyle . --exclude=.venv --max-line-length=120 --indent-size=4
+          pycodestyle . --exclude=.venv --max-line-length=120 --indent-size=4
+          pycodestyle_exit_code=$?
+          isort --check-only .
+          isort_exit_code=$?
+          
+          if [ $pycodestyle_exit_code -ne 0 ] || [ $isort_exit_code -ne 0 ]; then
+            echo "Code quality check failed."
+            exit 1
+          else
+            echo "Code quality check passed."
+          fi
 
   build-image:
     runs-on: ubuntu-latest
@@ -88,8 +112,6 @@ jobs:
               --build-arg ELASTIC_APM_SERVER_URL="${{ secrets.ELASTIC_APM_SERVER_URL }}" \
               --build-arg ELASTIC_APM_SECRET_TOKEN="${{ secrets.ELASTIC_APM_SECRET_TOKEN }}" \
               --tag inference:latest \
-              --tag inference:$IMAGE_TAG \
-              --tag inference:$COMMIT_HASH \
               -f Dockerfile .
 
             # Save the built Docker image as an artifact
@@ -139,112 +161,16 @@ jobs:
             gcloud auth configure-docker $GCR_HOST -q
             docker push $GCR_HOST/${{ secrets.GCP_PROJECT_ID }}/$GCR_REPOSITORY/inference
 
-  # deploy-on-cloud-run:
-  #   runs-on: ubuntu-latest
-  #   env:
-  #     GCR_HOST: ${{ vars.GCR_HOST }}
-  #     GCR_REPOSITORY: ${{ vars.GCR_REPOSITORY }}
+  deploy-on-cloud-run:
+    runs-on: ubuntu-latest
+    needs: build-image
+    if: github.event_name == 'workflow_dispatch'  # Run only when manually triggered
+    env:
+      GCR_HOST: ${{ vars.GCR_HOST }}
+      GCR_REPOSITORY: ${{ vars.GCR_REPOSITORY }}
 
-  #   # permissions:
-  #   #   contents: 'read'
-  #   #   id-token: 'write'
-
-  #   steps:
-  #     # - name: Configure GCP Credentials
-  #     #   uses: nightstory/gcp-secrets-action@v1
-  #     #   with:
-  #     #     gcp_credentials_json: ${{ secrets.GCP_CREDENTIALS_JSON }}
-  #     #     template_file: ./.github/template.yaml
-      
-  #     # - name: Authenticate to Google Cloud
-  #     #   id: 'auth'
-  #     #   uses: 'google-github-actions/auth@v2'
-  #     #   with:
-  #     #     project_id: ${{ secrets.GCP_PROJECT_ID }}
-  #     #     workload_identity_provider: 'projects/343693069423/locations/global/workloadIdentityPools/github/providers/mlops'
-  #     #     service_account: 'model-884@mlops-413215.iam.gserviceaccount.com'
-     
-  #     - name: Deploy service to Cloud Run
-  #       run: |
-  #           gcloud run deploy inference --image $GCR_HOST/${{ secrets.GCP_PROJECT_ID }}/$GCR_REPOSITORY/inference --max-instances=4 --platform managed --region asia-south1 --allow-unauthenticated
-
-  # mlops-container:
-  #   runs-on: ubuntu-latest
-  #   env:
-  #     GCS_TRAINED_MODELS_BUCKET_URI: ${{ vars.GCS_TRAINED_MODELS_BUCKET_URI }}
-  #     GCR_HOST: ${{ vars.GCR_HOST }}
-  #     GCR_REPOSITORY: ${{ vars.GCR_REPOSITORY }}
-  #     GCP_SERVICE_ACCOUNT_EMAIL: ${{ vars.GCP_SERVICE_ACCOUNT_EMAIL }}
-
-  #   permissions:
-  #     contents: 'read'
-  #     id-token: 'write'
-
-  #   steps:
-  #     - name: Checkout Reposiotry
-  #       uses: actions/checkout@v4
-  #       with:
-  #         repository: ${{ github.repository }}
-  #         ref: ${{ github.ref }}
-
-  #     - name: Configure GCP Credentials
-  #       uses: nightstory/gcp-secrets-action@v1
-  #       with:
-  #         gcp_credentials_json: ${{ secrets.GCP_CREDENTIALS_JSON }}
-  #         template_file: ./.github/template.yaml
-      
-  #     - name: Authenticate to Google Cloud
-  #       id: 'auth'
-  #       uses: 'google-github-actions/auth@v2'
-  #       with:
-  #         project_id: ${{ secrets.GCP_PROJECT_ID }}
-  #         workload_identity_provider: 'projects/343693069423/locations/global/workloadIdentityPools/github/providers/mlops'
-  #         service_account: 'model-884@mlops-413215.iam.gserviceaccount.com'
-
-  #     - name: Secrets to file
-  #       uses: mobiledevops/secret-to-file-action@v1
-  #       with:
-  #         base64-encoded-secret: ${{ secrets.GCP_CREDENTIALS_JSON }}
-  #         filename: "gcp-credentials.json"
-  #         is-executable: true
-  #         working-directory: "./"
-
-  #     - name: Build Docker Image
-  #       run: |
-  #           echo "Trained Models Bucket URI: $GCS_TRAINED_MODELS_BUCKET_URI"
-
-  #           COMMIT_HASH=$(git rev-parse --short HEAD)
-  #           IMAGE_TAG=$(git describe --tags --always)
-
-  #           echo "Commit Hash: $COMMIT_HASH"
-  #           echo "Image Tag: $IMAGE_TAG"
-
-  #           docker buildx build \
-  #             --progress auto \
-  #             --build-arg GCP_CREDENTIALS_JSON=gcp-credentials.json \
-  #             --build-arg GCP_PROJECT_ID="${{ secrets.GCP_PROJECT_ID }}" \
-  #             --build-arg GCS_TRAINED_MODELS_BUCKET_URI="$GCS_TRAINED_MODELS_BUCKET_URI" \
-  #             --build-arg ELASTIC_APM_SERVER_URL="${{ secrets.ELASTIC_APM_SERVER_URL }}" \
-  #             --build-arg ELASTIC_APM_SECRET_TOKEN="${{ secrets.ELASTIC_APM_SECRET_TOKEN }}" \
-  #             --tag inference:latest \
-  #             --tag inference:$IMAGE_TAG \
-  #             --tag inference:$COMMIT_HASH \
-  #             -f Dockerfile .
-
-  #           docker run -d -p 8000:8000 --name inference_container inference:latest
-
-  #     - name: Push Docker Image to GCR
-  #       run: |
-  #           echo "GCR Host: $GCR_HOST"
-            
-  #           docker tag inference:latest $GCR_HOST/${{ secrets.GCP_PROJECT_ID }}/$GCR_REPOSITORY/inference:latest
-            
-  #           docker images | grep inference
-  #           gcloud auth activate-service-account --key-file=gcp-credentials.json
-  #           gcloud auth configure-docker $GCR_HOST -q
-  #           docker push $GCR_HOST/${{ secrets.GCP_PROJECT_ID }}/$GCR_REPOSITORY/inference
-
-      
-  #     - name: Deploy service to Cloud Run
-  #       run: |
-  #           gcloud run deploy inference --image $GCR_HOST/${{ secrets.GCP_PROJECT_ID }}/$GCR_REPOSITORY/inference --max-instances=4 --platform managed --region asia-south1 --allow-unauthenticated
+    steps:
+      - name: Deploy service to Cloud Run
+        run: |
+            echo "Deploying to ${{ github.event.inputs.environment }} environment"
+            gcloud run deploy inference --image $GCR_HOST/${{ secrets.GCP_PROJECT_ID }}/$GCR_REPOSITORY/inference --max-instances=4 --platform managed --region asia-south1 --allow-unauthenticated
